services:

  redis:
    image: redis:7-alpine
    container_name: drl-redis

    ports:
      - "6379:6379"

    networks:
      - drl-network


  app1:
    image: distributed-rate-limiter
    container_name: drl-app1

    ports:
      - "8080:8080"

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

    networks:
      - drl-network


  app2:
    image: distributed-rate-limiter
    container_name: drl-app2

    ports:
      - "8081:8080"

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

    networks:
      - drl-network


  app3:
    image: distributed-rate-limiter
    container_name: drl-app3

    ports:
      - "8082:8080"

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

    networks:
      - drl-network


networks:
  drl-network:
    driver: bridge