spring.config.activate.on-profile=benchmark

############################################################
# Benchmark Rule
############################################################

rate-limiter.rules.benchmark.limit=${BENCHMARK_LIMIT:100}
rate-limiter.rules.benchmark.window=${BENCHMARK_WINDOW:1m}
rate-limiter.rules.benchmark.algorithm=${BENCHMARK_ALGORITHM:TOKEN_BUCKET}

############################################################
# Benchmark Diagnostics
############################################################

benchmark.diagnostics.enabled=true
benchmark.diagnostics.instance=${HOSTNAME:local}