spring.application.name=distributed-rate-limiter
spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Always show health details
management.endpoint.health.show-details=always

# Enable Prometheus endpoint
management.endpoint.prometheus.access=unrestricted

management.metrics.enable.all=true

management.metrics.distribution.percentiles-histogram.ratelimiter.request.duration=true

management.metrics.distribution.percentiles.ratelimiter.request.duration=0.5,0.95,0.99

rate-limiter.rules.demo.limit=5
rate-limiter.rules.demo.window=10s
rate-limiter.rules.demo.algorithm=TOKEN_BUCKET

rate-limiter.rules.payments.limit=20
rate-limiter.rules.payments.window=1m
rate-limiter.rules.payments.algorithm=SLIDING_WINDOW_COUNTER

rate-limiter.rules.search.limit=100
rate-limiter.rules.search.window=1m
rate-limiter.rules.search.algorithm=FIXED_WINDOW
